shellEmulator: true
trustPolicy: no-downgrade
packages:
  - packages/*
  - playground/*

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@types/lodash.camelcase': ^4.3.9
  '@types/lodash.snakecase': ^4.1.9
  '@types/node': ^24.10.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.8.1
  '@wry-smile/utils': ^1.1.2
  bumpp: ^10.4.0
  chalk: ^5.6.2
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.1
  lodash.camelcase: ^4.3.0
  lodash.snakecase: ^4.1.1
  picocolors: ^1.1.1
  tsdown: ^0.20.1
  typescript: ~5.9.3
  vite: ^7.2.4
  vue: ^3.5.24
  vue-tsc: ^3.1.4
